<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>WarframeMarketApp</RootNamespace>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1.0+v0.23.0</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Masa.Blazor" Version="1.11.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.80" />
    <PackageReference Include="Humanizer.Core.zh-Hans" Version="3.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
    <PackageReference Include="zms9110750.TreeCollection" Version="1.1.1" />
    <ProjectReference Include="..\..\src\WarframeMarketApi\WarframeMarketApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Update="赋能包配置.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ui-config.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>