<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <Description>Warframe.Market API 的 .NET 封装库</Description>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Title>WarframeMarketApi</Title>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>Warframe Market API</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);IS_LIB</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit.HttpClientFactory" Version="12.0.0" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Polly.RateLimiting" Version="8.7.0" />
    <PackageReference Include="zms9110750.TreeCollection" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
